# Site settings
title: Zach Blumenfeld - Technical Project Portfolio
author:
  name: Zach Blumenfeld
  email: zblumenf@gmail.com
description: "A sampling of demos and coded examples for AI, ML & Data Science"

# Build settings
remote_theme: jekyll-theme-cayman